anchor_version = "0.19.0"

[workspace]
members = ["programs/merkle-call-options"]

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"

[programs.localnet]
merkle_call_options = "tsTaDvb83Zv8fTm5HKZb4Lk9TQdPfYcSieqtV5JLgPk"
