[programs.localnet]
merkle_call_options = "B9WjjujXFUZUMfqKRTg5wutnVexM2nfpTL7LumWZKbT4"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/danah/.config/solana/id.json"

[scripts]
test = "mocha -t 1000000 tests/"
